- name: Create directories and set permissions
  hosts: ec2
  become: yes
  gather_facts: no
  tasks:
    - name: Create directories and set permissions
      shell: |
        mkdir -p /var/lib/demodir &&
        chmod 0755 /var/lib/demodir &&
        mkdir -p /var/lib/anotherdir &&
        chmod 0700 /var/lib/anotherdir
      remote_user: ubuntu
