- name: installing packages to server
  hosts: ec2
  become: yes
  gather_facts: no
  tasks:
    - name: Install Python 3
      become: yes
      raw: apt-get update && apt-get install -y python3
      remote_user: ubuntu

    - name: Install AWS CLI
      become: yes
      raw: apt-get update && apt-get install -y awscli
      remote_user: ubuntu

    - name: Install snapd
      become: yes
      raw: apt-get update && apt-get install -y snapd
      remote_user: ubuntu

    - name: Install k9s using snap
      become: yes
      shell: snap install k9s
      remote_user: ubuntu
