- name: Deploy to EC2 instance
  hosts: ec2
  become: yes
  gather_facts: no  # Disable gathering facts
  vars:
    ansible_ssh_private_key_file: "/var/lib/jenkins/keypairs/jenkins-test-server2-keypair.pem"
  tasks:
    - name: Create directory
      file:
        path: /var/lib/demodir
        state: directory
      remote_user: ubuntu
