- name: Create directories and set permissions
  hosts: ec2
  become: yes
  gather_facts: no
  tasks:
    - name: Create directories and set permissions
      shell: |
        mkdir -p /home/ubuntu/efs &&
        chmod 0755 //home/ubuntu/efs &&
        mkdir -p /home/ubuntu/efs/consul &&
        chmod 0700 /home/ubuntu/efs/consul
      remote_user: ubuntu
