- name: Attach EFS to server
  hosts: ec2
  become: yes
  gather_facts: no
  tasks:
    - name: Create directory
      raw: mkdir -p /home/ubuntu/efs
      remote_user: ubuntu

    - name: Install nfs-common
      raw: apt-get install -y nfs-common
      remote_user: ubuntu

    - name: Install python3-pip
      raw: |
        apt-get update
        apt-get install -y python3-pip
      remote_user: ubuntu

    - name: Install awscli
      raw: snap install aws-cli --classic --channel=stable
      remote_user: ubuntu


    - name: Install git
      raw: apt-get install -y git
      remote_user: ubuntu

    - name: Install psql-client
      raw: apt-get install -y postgresql-client
      remote_user: ubuntu

    - name: Install redis-tool
      raw: apt-get install -y redis-tools
      remote_user: ubuntu

    - name: Install kubectl
      raw: snap install kubectl --classic --channel=stable
      remote_user: ubuntu

    - name: Install k9s
      raw: snap install k9s --channel=stable
      remote_user: ubuntu

    - name: Install Helm
      raw: |
        curl -fsSL https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-add-repository "deb https://baltocdn.com/helm/stable/debian/ all main"
        sudo apt update
        sudo apt install -y helm
      remote_user: ubuntu


    

    - name: Mount EFS
      raw: sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport {{ efs_dns_name }}:/ /home/ubuntu/efs
      remote_user: ubuntu

    - name: Create directories and set permissions
      raw: |
        mkdir -p /home/ubuntu/efs/elasticsearch
        chmod 0755 /home/ubuntu/efs/elasticsearch
        mkdir -p /home/ubuntu/efs/elasticsearch/elasticsearch-0
        chmod 0777 /home/ubuntu/efs/elasticsearch/elasticsearch-0
        mkdir -p /home/ubuntu/efs/elasticsearch/elasticsearch-1
        chmod 0777 /home/ubuntu/efs/elasticsearch/elasticsearch-1
        mkdir -p /home/ubuntu/efs/elasticsearch/elasticsearch-2
        chmod 0777 /home/ubuntu/efs/elasticsearch/elasticsearch-2
        mkdir -p /home/ubuntu/efs/elasticsearch/elasticsearch-3
        chmod 0777 /home/ubuntu/efs/elasticsearch/elasticsearch-3
        mkdir -p /home/ubuntu/efs/kafka
        chmod 0755 /home/ubuntu/efs/kafka
        mkdir -p /home/ubuntu/efs/kafka/kafka-0
        chmod 0777 /home/ubuntu/efs/kafka/kafka-0
        mkdir -p /home/ubuntu/efs/kafka/kafka-1
        chmod 0777 /home/ubuntu/efs/kafka/kafka-1
        mkdir -p /home/ubuntu/efs/kafka/kafka-2
        chmod 0777 /home/ubuntu/efs/kafka/kafka-2
        mkdir -p /home/ubuntu/efs/kafka/kafka-3
        chmod 0777 /home/ubuntu/efs/kafka/kafka-3
        mkdir -p /home/ubuntu/efs/loggingagent
        chmod 0755 /home/ubuntu/efs/loggingagent
        mkdir -p /home/ubuntu/efs/loggingagent/logging-agent-0
        chmod 0777 /home/ubuntu/efs/loggingagent/logging-agent-0
        mkdir -p /home/ubuntu/efs/loggingagent/logging-agent-1
        chmod 0777 /home/ubuntu/efs/loggingagent/logging-agent-1
        mkdir -p /home/ubuntu/efs/loggingagent/logging-agent-2
        chmod 0777 /home/ubuntu/efs/loggingagent/logging-agent-2
        mkdir -p /home/ubuntu/efs/loggingagent/logging-agent-3
        chmod 0777 /home/ubuntu/efs/loggingagent/logging-agent-3
        mkdir -p /home/ubuntu/efs/loggingagent/logging-agent-4
        chmod 0777 /home/ubuntu/efs/loggingagent/logging-agent-4
      remote_user: ubuntu
